apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: farms.k8s.native-lb
spec:
  group: k8s.native-lb
  names:
    kind: Farm
    plural: farms
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            cluster:
              type: string
            ports:
              items:
                type: object
              type: array
            servers:
              type: object
            serviceName:
              type: string
            serviceNamespace:
              type: string
          required:
          - serviceName
          - serviceNamespace
          - cluster
          - ports
          - servers
          type: object
        status:
          properties:
            connectionStatus:
              type: string
            ipAdress:
              type: string
            lastUpdate:
              format: date-time
              type: string
            nodeList:
              items:
                type: string
              type: array
          type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
