apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: backends.k8s.native-lb
spec:
  group: k8s.native-lb
  names:
    kind: Backend
    plural: backends
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            host:
              type: string
            port:
              type: string
            priority:
              format: int64
              type: integer
            weight:
              format: int64
              type: integer
          required:
          - host
          - port
          type: object
        status:
          properties:
            activeConnections:
              format: int64
              type: integer
            live:
              type: boolean
            refusedConnections:
              format: int64
              type: integer
            rx:
              format: int64
              type: integer
            rxSecond:
              format: int64
              type: integer
            totalConnections:
              format: int64
              type: integer
            tx:
              format: int64
              type: integer
            txSecond:
              format: int64
              type: integer
          required:
          - live
          - totalConnections
          - activeConnections
          - refusedConnections
          - rx
          - tx
          - rxSecond
          - txSecond
          type: object
      required:
      - spec
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
