apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: agents.k8s.native-lb
spec:
  group: k8s.native-lb
  names:
    kind: Agent
    plural: agents
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            hostName:
              type: string
            ipAddress:
              type: string
          required:
          - hostName
          - ipAddress
          type: object
        status:
          properties:
            connectionStatus:
              type: string
            pid:
              format: int64
              type: integer
            startTime:
              type: string
            time:
              type: string
            uptime:
              format: int64
              type: integer
            version:
              type: string
          type: object
      required:
      - spec
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
