apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: clusters.k8s.native-lb
spec:
  group: k8s.native-lb
  names:
    kind: Cluster
    plural: clusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            default:
              description: 'Only one can exist true: any service of type loadbalancer
                will be created on the cluster false: only services with the cluster
                annotation name will be created on the cluster'
              type: boolean
            internal:
              description: 'true: Point pods as backends false: Point nodes as service
                backends'
              type: boolean
            rangeEnd:
              type: string
            rangeStart:
              type: string
            subnet:
              description: subnet to allocate from.
              type: string
            type:
              description: Cluster Type (NativeAgent,Custom) default NativeAgent
              type: string
          required:
          - subnet
          type: object
        status:
          properties:
            AllocatedNamespaces:
              type: object
            agents:
              type: object
            allocatedIps:
              type: object
            connectionStatus:
              type: string
            lastUpdate:
              format: date-time
              type: string
          required:
          - connectionStatus
          - lastUpdate
          type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
