apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: clusters.k8s.native-lb
spec:
  group: k8s.native-lb
  names:
    kind: Cluster
    plural: clusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            default:
              type: boolean
            internal:
              type: boolean
            ipRange:
              type: string
          required:
          - ipRange
          type: object
        status:
          properties:
            agents:
              type: object
            allocatedIps:
              type: object
            connectionStatus:
              type: string
            lastUpdate:
              format: date-time
              type: string
          required:
          - connectionStatus
          - lastUpdate
          type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
