apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: servers.k8s.native-lb
spec:
  group: k8s.native-lb
  names:
    kind: Server
    plural: servers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            backendConnectionTimeout:
              type: string
            backendIdleTimeout:
              type: string
            balance:
              type: string
            bind:
              type: string
            clientIdleTimeout:
              type: string
            discovery:
              properties:
                backend:
                  items:
                    properties:
                      host:
                        type: string
                      port:
                        format: int32
                        type: integer
                      priority:
                        format: int64
                        type: integer
                      weight:
                        format: int64
                        type: integer
                    required:
                    - host
                    - port
                    type: object
                  type: array
                kind:
                  type: string
              required:
              - kind
              - backend
              type: object
            healthCheck:
              properties:
                fails:
                  format: int64
                  type: integer
                interval:
                  type: string
                kind:
                  type: string
                passes:
                  format: int64
                  type: integer
                pingTimeoutDuration:
                  type: string
                timeout:
                  type: string
              type: object
            maxConnections:
              format: int64
              type: integer
            port:
              format: int32
              type: integer
            protocol:
              type: string
            udp:
              properties:
                maxRequests:
                  format: int64
                  type: integer
                maxResponses:
                  format: int64
                  type: integer
              type: object
          required:
          - bind
          - port
          - protocol
          - balance
          - maxConnections
          - clientIdleTimeout
          - backendIdleTimeout
          - backendConnectionTimeout
          - discovery
          type: object
        status:
          properties:
            activeConnections:
              format: int64
              type: integer
            rxSecond:
              format: int64
              type: integer
            rxTotal:
              format: int64
              type: integer
            txSecond:
              format: int64
              type: integer
            txTotal:
              format: int64
              type: integer
          type: object
      required:
      - spec
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
