---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: nativelb
---
apiVersion: k8s.native-lb/v1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    k8s.nativelb.default: "true"
  name: cluster-sample-internal
  namespace: nativelb
spec:
  # Add fields here
  url: 127.0.0.1:8050
  default: true
  internal: true
  ipRange: "10.0.0.0/24"
