---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service2
  namespace: nginx2
  annotations:
    k8s.nativelb.io/cluster: "cluster-internal"
spec:
  selector:
    app: nginx2
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer