---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: nginx1
  annotations:
    k8s.nativelb.io/cluster: "cluster-internal"
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer
