---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: external-loadbalancer
---
apiVersion: manager.external-loadbalancer/v1alpha1
kind: Provider
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    external-loadbalancer-default: "true"
  name: provider-sample
  namespace: external-loadbalancer
spec:
  # Add fields here
  url: 127.0.0.1:8050
  default: true
