---
apiVersion: k8s.native-lb/v1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    k8s.nativelb.default: "true"
  name: cluster-internal
  namespace: nativelb
spec:
  default: true
  internal: true
  subnet: "10.0.0.0/24"
