apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - manager.external-loadbalancer
  resources:
  - farms
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - manager.external-loadbalancer
  resources:
  - providers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: external-loadbalancer
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: farms.manager.external-loadbalancer
spec:
  group: manager.external-loadbalancer
  names:
    kind: Farm
    plural: farms
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            ports:
              items:
                type: object
              type: array
            provider:
              type: string
            serviceName:
              type: string
            serviceNamespace:
              type: string
          required:
          - serviceName
          - serviceNamespace
          - provider
          - ports
          type: object
        status:
          properties:
            connectionStatus:
              type: string
            ipAdress:
              type: string
            lastUpdate:
              format: date-time
              type: string
            nodeList:
              items:
                type: string
              type: array
          type: object
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: providers.manager.external-loadbalancer
spec:
  group: manager.external-loadbalancer
  names:
    kind: Provider
    plural: providers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            default:
              type: boolean
            url:
              type: string
          required:
          - url
          type: object
        status:
          properties:
            connectionStatus:
              type: string
          type: object
  version: v1alpha1
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: external-loadbalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-loadbalancer-controller
  namespace: external-loadbalancer
  labels:
    control-plane: external-loadbalancer-controller
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: external-loadbalancer-controller
      controller-tools.k8s.io: "1.0"
  template:
    metadata:
      labels:
        control-plane: external-loadbalancer-controller
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - command:
        - /root/manager
        image: quay.io/k8s-external-loadbalancer/controller:latest
        name: manager
        resources:
          limits:
            cpu: 500m
            memory: 300Mi
          requests:
            cpu: 500m
            memory: 100Mi
      terminationGracePeriodSeconds: 10