---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: nativelb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nativelb-controller
  namespace: nativelb
  labels:
    control-plane: nativelb-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: nativelb-controller
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        scheduler.alpha.kubernetes.io/tolerations: |
          [
            {
              "key": "CriticalAddonsOnly",
              "operator": "Exists"
            }
          ]
      labels:
        control-plane: nativelb-controller
    spec:
      containers:
      - image: quay.io/k8s-nativelb/nativelb-controller:latest
        imagePullPolicy: IfNotPresent
        name: controller
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 200Mi
      terminationGracePeriodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: nativelb-controller
  namespace: nativelb
spec:
  selector:
    control-plane: nativelb-controller
  ports:
  - protocol: TCP
    port: 8080