---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: nativelb
---
apiVersion: k8s.native-lb/v1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cluster-sample-cluster
  namespace: nativelb
spec:
  default: false
  internal: true
  subnet: "10.0.0.0/24"
  rangeStart: "10.0.0.10"
