---
apiVersion: k8s.native-lb/v1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: cluster-external
  namespace: nativelb
spec:
  default: false
  internal: false
  subnet: "10.192.0.0/24"
  rangeStart: "10.192.0.70"
  rangeEnd: "10.192.0.90"
