---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: nativelb
---
apiVersion: k8s.native-lb/v1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  #    k8s.nativelb.default: "true"
  name: cluster-sample-external
  namespace: nativelb
spec:
  # Add fields here
  default: false
  internal: false
  ipRange: "11.0.0.0/24"
