---
apiVersion: k8s.native-lb/v1
kind: Cluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    k8s.nativelb.io/default: "true"
  name: cluster-internal
  namespace: nativelb
spec:
  default: true
  internal: true
  subnet: "10.192.0.0/24"
  rangeStart: "10.192.0.70"
  rangeEnd: "10.192.0.90"

