---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: nativelb
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nativelb-agent
  namespace: nativelb
  labels:
    control-plane: nativelb-agent
spec:
  selector:
    matchLabels:
      control-plane: nativelb-agent
  template:
    metadata:
      labels:
        control-plane: nativelb-agent
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostNetwork: true
      containers:
      - name: agent
        image: registry:5000/k8s-nativelb/nativelb-agent:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: nativelb-config
      terminationGracePeriodSeconds: 30