apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: agents.k8s.native-lb
spec:
  group: k8s.native-lb
  names:
    kind: Agent
    plural: agents
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            cluster:
              type: string
            hostName:
              type: string
            ipAddress:
              type: string
            operational:
              type: boolean
            port:
              format: int32
              type: integer
          required:
          - hostName
          - ipAddress
          - port
          - cluster
          - operational
          type: object
        status:
          properties:
            KeepAlivedPid:
              format: int64
              type: integer
            connectionStatus:
              type: string
            lastUpdate:
              format: date-time
              type: string
            lbPid:
              format: int64
              type: integer
            operationStatus:
              type: string
            startTime:
              type: string
            time:
              type: string
            uptime:
              format: int64
              type: integer
            version:
              type: string
          type: object
      required:
      - spec
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
